name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}] # Isso fará a ação rodar uma vez por dia
  workflow_dispatch:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          
          # Configuração do gráfico de Estatísticas Gerais
          plugin_general: yes
          filename: general.svg
          base: header, activity, community, repositories, metadata
          
          # Configuração do gráfico de Linguagens
          plugin_languages: yes
          filename: languages.svg
          plugin_languages_ignored: html, css, tex, less, dockerfile, makefile, qmake, lex, cmake, shell, gnuplot # Ignora linguagens comuns
          plugin_languages_limit: 8 # Número máximo de linguagens a mostrar
